name: CI_CD UserRegistration

on:
  push:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chechkout@v2
      - run: npm ci
      - run: npm test
      # - name: Test Report
      #   uses: dorny/test-reporter@v1
      #   if: success() || failure() # run this step even if previous step failed
      #   with:
      #     name: JEST Tests # Name of the check run which will be created
      #     path: reports/jest-*.xml # Path to test results
      #     reporter: jest-junit # Format of test results

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "limitless-gorge-95066" #Must be unique in Heroku
          heroku_email: "zeatgomez@gmail.com"
          usedocker: true
